In [63]:
#dataset_link:https://www.kaggle.com/bahramjannesarr/goodreads-book-datasets-10m
import pandas as pd
good_reads = pd.read_csv('book1-100k.csv' , low_memory=False)
good_reads = good_reads[good_reads['Language'] == 'eng']

In [64]:
#good_reads.head(5)
good_reads2 = good_reads[['Name' , 'RatingDistTotal' , 'Publisher' , 'Authors' , 'Rating' ]]
good_reads2.head(5)

,Name,RatingDistTotal,Publisher,Authors,Rating
0,Harry Potter and the Half-Blood Prince (Harry ...,total:2298124,Scholastic Inc.,J.K. Rowling,4.57
1,Harry Potter and the Order of the Phoenix (Har...,total:2358637,Scholastic Inc.,J.K. Rowling,4.50
2,Harry Potter and the Sorcerer's Stone (Harry P...,total:6587388,Scholastic Inc,J.K. Rowling,4.47
3,Harry Potter and the Chamber of Secrets (Harry...,total:2560657,Scholastic,J.K. Rowling,4.42
4,Harry Potter and the Prisoner of Azkaban (Harr...,total:2610317,Scholastic Inc.,J.K. Rowling,4.57

In [65]:
good_reads2['RatingDistTotal']

0        total:2298124
1        total:2358637
2        total:6587388
3        total:2560657
4        total:2610317
             ...
58260        total:265
58262      total:11162
58265       total:3666
58280         total:25
58281         total:51
Name: RatingDistTotal, Length: 15988, dtype: object

In [76]:
total_vots["total_vote"] = good_reads2.RatingDistTotal.str.extract('(\d+)')
good_reads2['total_votes'] = total_vots['total_vote'] 
good_reads2.head(5)

<ipython-input-76-9c0f8e267ac4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  good_reads2['total_votes'] = total_vots['total_vote']

,Name,RatingDistTotal,Publisher,Authors,Rating,total_votes
0,Harry Potter and the Half-Blood Prince (Harry ...,total:2298124,Scholastic Inc.,J.K. Rowling,4.57,2298124
1,Harry Potter and the Order of the Phoenix (Har...,total:2358637,Scholastic Inc.,J.K. Rowling,4.50,2358637
2,Harry Potter and the Sorcerer's Stone (Harry P...,total:6587388,Scholastic Inc,J.K. Rowling,4.47,6587388
3,Harry Potter and the Chamber of Secrets (Harry...,total:2560657,Scholastic,J.K. Rowling,4.42,2560657
4,Harry Potter and the Prisoner of Azkaban (Harr...,total:2610317,Scholastic Inc.,J.K. Rowling,4.57,2610317

In [43]:
good_reads2['total_votes'] = total_rating['total_rating']

<ipython-input-43-04fe1b013bd5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  good_reads2['total_votes'] = total_rating['total_rating']

In [44]:
good_reads2.drop('RatingDistTotal', axis=1 , inplace=True)

/home/amir/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [45]:
good_reads2

,Name,Publisher,Authors,Rating,total_votes
0,Harry Potter and the Half-Blood Prince (Harry ...,Scholastic Inc.,J.K. Rowling,4.57,2298124
1,Harry Potter and the Order of the Phoenix (Har...,Scholastic Inc.,J.K. Rowling,4.50,2358637
2,Harry Potter and the Sorcerer's Stone (Harry P...,Scholastic Inc,J.K. Rowling,4.47,6587388
3,Harry Potter and the Chamber of Secrets (Harry...,Scholastic,J.K. Rowling,4.42,2560657
4,Harry Potter and the Prisoner of Azkaban (Harr...,Scholastic Inc.,J.K. Rowling,4.57,2610317
...,...,...,...,...,...
58260,Thomas Paine and the Promise of America (Oxfor...,Hill and Wang,Harvey J. Kaye,3.91,265
58262,Common Sense and Other Writings,Barnes Noble Classics,Thomas Paine,3.91,11162
58265,Faith of My Fathers: A Family Memoir,William Morrow Paperbacks,John McCain,3.86,3666
58280,Science Fiction: The Best of 2001,Fantastic Audio,Robert Silverberg,3.48,25
58281,Nebula Awards Showcase 2001,Mariner Books,Robert Silverberg,3.82,51

In [89]:
good_reads2['total_votes'] = good_reads2['total_votes'].astype(float)
C = good_reads2['Rating'].mean()
m = good_reads2['total_votes'].quantile(0.90)
q_books = good_reads2.copy().loc[good_reads2['total_votes'] >= m]
m

<ipython-input-89-017ec751d696>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  good_reads2['total_votes'] = good_reads2['total_votes'].astype(float)

42348.60000000002

In [90]:
def weighted_rating(x, m=m, C=C):
    v = x['total_votes']
    R = x['Rating']
    # Calculation based on the IMDB formula
    return (v/(v+m) * R) + (m/(m+v) * C)
q_books['score'] = q_books.apply(weighted_rating, axis=1)
q_books = q_books.sort_values('score', ascending=False)
q_books.head(5)
q_books.drop('RatingDistTotal' , axis = 1 , inplace = True)
q_books.drop('Publisher' , axis = 1 , inplace = True)
q_books.head(20)

,Name,Authors,Rating,total_votes,score
41331,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,4.62,2661573.0,4.609173
4,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,4.57,2610317.0,4.559762
54174,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.57,2306655.0,4.558439
40728,Harry Potter and the Half-blood Prince (Harry ...,J.K. Rowling,4.57,2300327.0,4.558407
0,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,4.57,2298124.0,4.558397
5,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,4.56,2431085.0,4.549191
9245,"The Return of the King (The Lord of the Rings,...",J.R.R. Tolkien,4.53,642807.0,4.492835
44758,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,2367353.0,4.489960
1,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,2358637.0,4.489924
44759,Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.47,6622480.0,4.466561
2703,Harry Potter and the Philosopher's Stone,J.K. Rowling,4.47,6588013.0,4.466543
2,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,4.47,6587388.0,4.466542
9321,The Lord of the Rings Millennium Edition Boxed...,J.R.R. Tolkien,4.50,539614.0,4.458428
23,"The Lord of the Rings (The Lord of the Rings, ...",J.R.R. Tolkien,4.50,539513.0,4.458421
27,The Lord of the Rings Box Set,J.R.R. Tolkien,4.50,539513.0,4.458421
3,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,2560657.0,4.412007
44874,"The Two Towers (The Lord of the Rings, #2)",J.R.R. Tolkien,4.44,677984.0,4.409941
9243,"The Two Towers (The Lord of the Rings, #2)",J.R.R. Tolkien,4.44,675727.0,4.409847
9294,The Lord of the Rings / The Hobbit,J.R.R. Tolkien,4.60,106636.0,4.409188
22,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,J.R.R. Tolkien,4.60,106621.0,4.409168

In [48]:
q_books['score'] = q_books.apply(weighted_rating, axis=1)

In [49]:
q_books = q_books.sort_values('score', ascending=False)
q_books.head(20)

,Name,Publisher,Authors,Rating,total_votes,score
41331,Harry Potter and the Deathly Hallows (Harry Po...,Arthur A. Levine Books,J.K. Rowling,4.62,2661573.0,4.609173
4,Harry Potter and the Prisoner of Azkaban (Harr...,Scholastic Inc.,J.K. Rowling,4.57,2610317.0,4.559762
54174,Harry Potter and the Half-Blood Prince (Harry ...,Bloomsbury Publishing,J.K. Rowling,4.57,2306655.0,4.558439
40728,Harry Potter and the Half-blood Prince (Harry ...,Turtleback Books,J.K. Rowling,4.57,2300327.0,4.558407
0,Harry Potter and the Half-Blood Prince (Harry ...,Scholastic Inc.,J.K. Rowling,4.57,2298124.0,4.558397
5,Harry Potter and the Goblet of Fire (Harry Pot...,Scholastic,J.K. Rowling,4.56,2431085.0,4.549191
9245,"The Return of the King (The Lord of the Rings,...",HarperCollins Publishers Ltd,J.R.R. Tolkien,4.53,642807.0,4.492835
44758,Harry Potter and the Order of the Phoenix (Har...,Arthur A. Levine Books / Scholastic Inc.,J.K. Rowling,4.50,2367353.0,4.489960
1,Harry Potter and the Order of the Phoenix (Har...,Scholastic Inc.,J.K. Rowling,4.50,2358637.0,4.489924
44759,Harry Potter and the Sorcerer's Stone,Arthur A. Levine Books / Scholastic Inc.,J.K. Rowling,4.47,6622480.0,4.466561
2703,Harry Potter and the Philosopher's Stone,Bloomsbury Publishing PLC,J.K. Rowling,4.47,6588013.0,4.466543
2,Harry Potter and the Sorcerer's Stone (Harry P...,Scholastic Inc,J.K. Rowling,4.47,6587388.0,4.466542
9321,The Lord of the Rings Millennium Edition Boxed...,Houghton Mifflin,J.R.R. Tolkien,4.50,539614.0,4.458428
23,"The Lord of the Rings (The Lord of the Rings, ...",Houghton Mifflin Harcourt,J.R.R. Tolkien,4.50,539513.0,4.458421
27,The Lord of the Rings Box Set,NaN,J.R.R. Tolkien,4.50,539513.0,4.458421
3,Harry Potter and the Chamber of Secrets (Harry...,Scholastic,J.K. Rowling,4.42,2560657.0,4.412007
44874,"The Two Towers (The Lord of the Rings, #2)",Houghton Mifflin Company,J.R.R. Tolkien,4.44,677984.0,4.409941
9243,"The Two Towers (The Lord of the Rings, #2)",Houghton Mifflin,J.R.R. Tolkien,4.44,675727.0,4.409847
9294,The Lord of the Rings / The Hobbit,Collins Modern Classics,J.R.R. Tolkien,4.60,106636.0,4.409188
22,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,Ballantine Books,J.R.R. Tolkien,4.60,106621.0,4.409168

In [39]:
good_reads.shape

(15988, 18)

In [38]:
good_reads

,Id,Name,RatingDist1,pagesNumber,RatingDist4,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,RatingDist2,RatingDist5,ISBN,RatingDist3
0,1,Harry Potter and the Half-Blood Prince (Harry ...,1:9896,652,4:556485,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,2:25317,5:1546466,NaN,3:159960
1,2,Harry Potter and the Order of the Phoenix (Har...,1:12455,870,4:604283,total:2358637,1,9,Scholastic Inc.,29770,2004,eng,J.K. Rowling,4.50,2:37005,5:1493113,0439358078,3:211781
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,1:108202,309,4:1513191,total:6587388,1,11,Scholastic Inc,75911,2003,eng,J.K. Rowling,4.47,2:130310,5:4268227,NaN,3:567458
3,4,Harry Potter and the Chamber of Secrets (Harry...,1:11896,352,4:706082,total:2560657,1,11,Scholastic,244,2003,eng,J.K. Rowling,4.42,2:49353,5:1504505,0439554896,3:288821
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,1:10128,435,4:630534,total:2610317,1,5,Scholastic Inc.,37093,2004,eng,J.K. Rowling,4.57,2:24849,5:1749958,043965548X,3:194848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58260,99958,Thomas Paine and the Promise of America (Oxfor...,1:6,336,4:87,total:265,25,7,Hill and Wang,31,2006,eng,Harvey J. Kaye,3.91,2:13,5:89,0809093448,3:70
58262,99962,Common Sense and Other Writings,1:207,432,4:3602,total:11162,1,11,Barnes Noble Classics,2,2005,eng,Thomas Paine,3.91,2:722,5:3863,1593083769,3:2768
58265,99965,Faith of My Fathers: A Family Memoir,1:52,368,4:1471,total:3666,22,8,William Morrow Paperbacks,288,2000,eng,John McCain,3.86,2:209,5:1004,0060957867,3:930
58280,99985,Science Fiction: The Best of 2001,1:1,0,4:6,total:25,1,8,Fantastic Audio,0,2002,eng,Robert Silverberg,3.48,2:2,5:5,157453503X,3:11
58281,99986,Nebula Awards Showcase 2001,1:0,272,4:20,total:51,26,4,Mariner Books,5,2001,eng,Robert Silverberg,3.82,2:2,5:12,0156013355,3:17

In [51]:
good_reads2[good_reads2['Name'] == 'A Farewell to Arms']

Empty DataFrame
Columns: [Name, Publisher, Authors, Rating, total_votes]
Index: []